function config = FELconfigRead() 
%
% config = FELconfigRead() 
% Returns in structure config the present value of parameter most relevant
% to FEL codes.
%
config = struct(...
'time', now,...
'beamEnergy', lcaGet('BEND:DMPH:400:BDES'),...
'vernier', lcaGet('SIOC:SYS0:ML00:AO289'),...
'BC2peakCurrentSetpoint', lcaGet('SIOC:SYS0:ML00:AO044'),...
'BC1peakCurrentSetpoint', lcaGet('SIOC:SYS0:ML00:AO016'),... 
'charge_nC', lcaGet('SIOC:SYS0:ML00:AO470'),...
...%'taper', segmentTranslate(),...
'photonEnergy', lcaGet('SIOC:SYS0:ML00:AO627'),... 
'attenuationSolid', lcaGet('SATT:FEE1:320:RACT'),...
'L1Sphase', lcaGet('ACCL:LI21:1:L1S_PDES'),...
'L1Xphase', lcaGet('ACCL:LI21:180:L1X_PDES'),...
'LaserHeaterEnergy', lcaGet('LASR:IN20:196:PWR1H'),...
'emittanceOTR2x', lcaGet('SIOC:SYS0:ML00:AO493'),...
'emittanceOTR2y', lcaGet('SIOC:SYS0:ML00:AO494')...
);