%
% set_status(handles, txt,  frac)
%
% Set text displayed in the status bar.
% If frac is present and not empty, a progress bar
% is displayed below the text. frac should be a number
% between 0 and 1.
%
function set_status(handles, txt,  frac)
    if (nargin < 3 || isempty(frac))
        display_percentage = false;
    else
        display_percentage = true;
    end
    
    cla(handles.axesStatus);
    hide_axis(handles.axesStatus);
    set(handles.axesStatus, 'Color', ...
        get(0, 'DefaultUIControlBackgroundColor'), ...
        'Units', 'normalized');

    if (display_percentage)
        patch([0 1 1 0], [0 0 1 1], [1 1 1], ...
             'Parent', handles.axesStatus);
        patch([0 frac frac 0], [0 0 1 1], [1 0 0], ...
             'Parent', handles.axesStatus);
    end

    if (display_percentage)
        text(0.5,0.5,txt, ...
            'Units', 'normalized', ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'middle', ...
            'Color', [0 0 0], ...
            'Parent', handles.axesStatus, ...
            'FontWeight', 'bold', ...
            'FontSize', 11, ...
            'Interpreter', 'none');
    else
        text(0, 0, txt, ...
            'Units', 'normalized', ...
            'HorizontalAlignment', 'left', ...
            'VerticalAlignment', 'bottom', ...
            'Color', [0 0 0], ...
            'Parent', handles.axesStatus, ...
            'FontWeight', 'normal', ...
            'FontSize', 11, ...
            'interpreter', 'none');
    end
    pause(1e-6);
return
