function sigE_E0 = synch_esprd(E,ang,L)

%	sigE_E0 = synch_esprd(E,ang,L);
%
%	Function to calculate incoherent relative rms energy spread generated by a bend of angle,
%	ang [rad], length, L [m], and at energy E [GeV].
%
%	Inputs:		E:			Electron energy [GeV]
%				ang:		Bend angle [rad]
%				L:			Beam pathg length through bend magnet [m]
%
%	Outputs:	sigE_E0:	Relative rms energy spread [ ]
%
%============================================================================================

sigE_E0 = sqrt(4.13E-11*E^5*abs(ang^3))/L;