function [fileName, pathName] = util_dataSave(data, header, name, ts, showDlg, useCurrent, fileExt)
%DATASAVE
%  DATASAVE(DATA, HEADER, NAME, TS, SHOWDLG, USECURRENT, FILEEXT) saves
%  DATA in autogenerated or user specified filename and location.

% Features: Saves the DATA in the
% $LCDATA/matlab/data/yyyy/yyyy-mm/yyyy-mm-dd directory as file named
% HEADER-NAME-datestr(TS).

% Input arguments:
%    DATA: Data to be saved
%    HEADER: Header of file name
%    NAME: PV name
%    TS: PV time stamp
%    SHOWDLG: Flag to open file save dialog
%    USECURRENT: Flag to use current path instead of automatic location
%        If set to a string, use this string as path
%    FILEEXT: Extension for file, default is .mat

% Output arguments:
%    FILENAME: File name returned from file open dialog. Empty if
%        cancelled
%    PATHNAME: Path to file. Empty if cancelled


% Compatibility: Version 7 and higher
% Called functions: none

% Author: Henrik Loos, SLAC

% --------------------------------------------------------------------
if nargin < 7, fileExt='.mat';end
if nargin < 6, useCurrent=0;end
if nargin < 5, showDlg=0;end

pathName=pwd;
if ischar(useCurrent)
    pathName=useCurrent;
    useCurrent=1;
end
if ~useCurrent
    dataDate=ts;
    dataRoot=fullfile(getenv('MATLABDATAFILES'),'data');
%    dataRoot='~/loos/data';
    dataYear=datestr(dataDate,'yyyy');
    dataMon=datestr(dataDate,'yyyy-mm');
    dataDay=datestr(dataDate,'yyyy-mm-dd');
    pathName=fullfile(dataRoot,dataYear,dataMon,dataDay);
    if ~exist(pathName,'dir'), try mkdir(pathName);catch end, end
end
fileName=strrep([header '-' name '-' datestr(ts,'yyyy-mm-dd-HHMMSS') fileExt],':','_');

name=fullfile(pathName,fileName);
str='';
if exist(name,'file') && ~showDlg
    str=questdlg(['File ',name,' already exists'],'File exists','Overwrite','Cancel','Save as ...','Overwrite');
    if strcmp(str,'Cancel'), return, end
end

if showDlg || strcmp(str,'Save as ...')
    [fileName,pathName]=uiputfile(fullfile(pathName,fileName),'Save as');
    if ~ischar(fileName), return, end
end

name=fullfile(pathName,fileName);
save(name,'data');
