function [data, fileName, pathName] = util_dataLoad(dlgTitle, useCurrent, fileExt)
%DATALOAD
%  DATALOAD(DLGTITLE, USECURRENT, FILEEXT) loads DATA from autogenerated or
%  user specified location.

% Features: Loads a data file as saved with the dataSave function from the
% $LCDATA/matlab/data/yyyy/yyyy-mm/yyyy-mm-dd directory.

% Input arguments:
%    DLGTITLE: Title of file open dialog
%    USECURRENT: Flag to use current path instead of automatic location,
%        which is the default. If set to a string, use this string as path
%    FILEEXT: Extension for file, default is .mat

% Output arguments:
%    DATA: data variable in matlab file
%    FILENAME: File name returned from file open dialog. Empty if
%        cancelled
%    PATHNAME: Path to file. Empty if cancelled

% Compatibility: Version 7 and higher
% Called functions: none

% Author: Henrik Loos, SLAC

% --------------------------------------------------------------------
if nargin < 3, fileExt='*.mat';end
if nargin < 2, useCurrent=0;end
if nargin < 1, dlgTitle='Load file';end

persistent pathPrev

data=[];

pathName=pwd;
if ischar(useCurrent)
    pathName=useCurrent;
    useCurrent=1;
end
if ~useCurrent
    dataDate=now;
    dataRoot=fullfile(getenv('MATLABDATAFILES'),'data');
    pathName=dataRoot;
    dataYear=datestr(dataDate,'yyyy');pathTest=fullfile(pathName,dataYear);
    if exist(pathTest,'dir'), pathName=pathTest;end
    dataMon=datestr(dataDate,'yyyy-mm');pathTest=fullfile(pathName,dataMon);
    if exist(pathTest,'dir'), pathName=pathTest;end
    dataDay=datestr(dataDate,'yyyy-mm-dd');pathTest=fullfile(pathName,dataDay);
    if exist(pathTest,'dir'), pathName=pathTest;end
end

if ~isempty(pathPrev), pathName=pathPrev;end

fileName=fileExt;
[fileName,pathName]=uigetfile(fullfile(pathName,fileName),dlgTitle);
if ~ischar(fileName), pathPrev=[];return, end

load(fullfile(pathName,fileName),'data');

pathPrev=pathName;
