#!/bin/bash -norc
#==============================================================
#
#  Abs:  Starts Matlab GUIs from an edm button push
#
#  Name: MatlabGUI
#
#  Facility:  SLAC
#
#  Auth: 16-Nov-2007,DFAIRLEY (dfairley@slac.stanford.edu)
#         created from MatlabGUI by M. Zelazny
#==============================================================
#
# Setup LCLS Environment
#
        if [ -f ${LCLS_ROOT}/tools/oracle/oracleSetup.bash ]; then
            source ${LCLS_ROOT}/tools/oracle/oracleSetup.bash
        fi

        if [ -f ${LCLS_ROOT}/physics/setup/javaSetup.bash ]; then
            source ${LCLS_ROOT}/physics/setup/javaSetup.bash 2>&1 > /dev/null
        fi

        if [ -f ${LCLS_ROOT}/epics/setup/fixed-epics-setup.bash ]; then
            source ${LCLS_ROOT}/epics/setup/fixed-epics-setup.bash
            if [ -f ${LCLS_ROOT}/epics/setup/epicsenv-3.14.12.bash ]; then
                source ${LCLS_ROOT}/epics/setup/epicsenv-3.14.12.bash
            fi
        fi

        export MATLAB_VER=2012a
        export EPICS_HOST_ARCH=linux-x86
        if [ -f ${LCLS_ROOT}/tools/matlab/setup/matlabSetup.bash ]; then
            source ${LCLS_ROOT}/tools/matlab/setup/matlabSetup.bash
            export PATH=${MATLAB_ROOT}/bin:$PATH
        fi

#
# Log file on nfs
#
    user=`whoami`-
    date=`date`
    year=`echo $date | cut -d" " -f6`-
    month=`echo $date | cut -d" " -f2`-
    day=`echo $date | cut -d" " -f3`-
    time=`echo $date | cut -d" " -f4 | cut -c1-5`

    if [ -e $MATLABDATAFILES/Feedback/log ]; then
      log_file=$MATLABDATAFILES/Feedback/log/$3/$1GUI$user$year$month$day$time.log
    else
      log_file=$1GUI$user$year$month$day$time.log
    fi 
#
# Start the Matlab script
#
  matlab -nosplash -nodesktop -glnx86 -r lcaInit,"$1('$2')" -logfile $log_file

  else
    echo "Sorry, can't find LCLS environment setup"
  fi

