#!/bin/bash -norc
#==============================================================
#
#  Abs:  Starts  Matlab scripts
#
#  Name: Matlab_startup_asta
#   $1 :  matlab script to start
#  [$2]:  Used by FeedbackGUI for config file
#  [$3]:  Used by FeedbackGUI for labeling log file
#
# Joe Frisch's Matlab files:
#     L23_set_phase
#     multiknob
#     phase_cavity_monitor
#     watcher
#     phase_control
#     laser_camera
#     archive_LLRF_ampl_phase
#
# ------------------------------------------------------------
# This script gets called from astahome which performs an
# SSH call to asta-srv02 and sets it's display to the
# Virtual frame buffer (XVFB) before launching this script.
# ------------------------------------------------------------
#
#  Facility:  SLAC
#
#  Auth: 31-Oct-2008, Brobeck
#         created from MatlabGUI by M. Zelazny
#
# Mod
#
# 8 July 2014 Garth Brown
#  Ported to ASTA/testfac environment
#
# 26-Apr-2010 Mike Zelazny
#  Set MATLAB_STARTUP_SCRIPT & MATLAB_LOG_FILE_NAME.
#
# 19-Nov-2008, Brobeck
#  added a $2 variable for use with the lcaInit,"$1('$2')" call
#  and $3 for labeling the log file
#
# 21-Nov-2008, Brobeck
#  Adding a log system to retain logs
#
#==============================================================
#
# Make sure acctf is running the script on asta-srv02
#

if  ! [ "$USER" = "acctf" ] && [ `uname -n` = "asta-srv02" ]
  then
     echo ""
     echo "This script must be run from the acctf or softegr account"
     echo "on asta-srv02 - Preferably from astahome"
     echo ""
     exit
fi

# Set the display
#
OLD_DISP=`echo $DISPLAY`
export DISPLAY=:1.0

#
# Setup ACCTEST Environment
#
  if [ -e ${ACCTEST_ROOT}/tools/matlab/setup/matlabSetup_acctest.bash ]; then
     . ${ACCTEST_ROOT}/tools/matlab/setup/matlabSetup_acctest.bash

#
# Log file on nfs -rename old one
#
    if [ -e $PHYSICS_DATA/log/matlab ]; then
      log_file=$PHYSICS_DATA/log/matlab/$1$3.log
    else
      log_file=$1$3.log
    fi

    MDATE=`date '+%d_%b_%Y_%H_%M'`
    if [ -e $log_file ]; then
       /bin/mv -f ${log_file} ${log_file}-$MDATE
    fi

#
# For accounting purposes (see startup.m)
#
    export MATLAB_STARTUP_SCRIPT=$1
    export MATLAB_LOG_FILE_NAME=$log_file
#
# Start the Matlab script
#
    if [ "$2" = "" ]; then
         xterm -e matlab -glnx86 -nodesktop -nosplash -r $1  -logfile $log_file &
      else
         xterm -e matlab -glnx86 -nodesktop -nosplash -r lcaInit,"$1('$2')"  -logfile $log_file &
    fi

    sleep 1
    export DISPLAY=$OLD_DISP
    xterm -e tail -f $log_file &

    #
    # log file cleanup -keep 5 log files
    #
    LOGCNT=`ls -t $PHYSICS_DATA/log/matlab/$1$3.log* | wc -l`
    if [ "$LOGCNT" -gt 5 ]; then
	y=`expr $LOGCNT - 5`
	for x in `ls -t  $PHYSICS_DATA/log/matlab/$1$3.log* | tail -n$y`
        do
	  /bin/rm -f $x
	done
    fi
  else
    echo "Sorry, can't find ACCTEST environment setup"
  fi

