#!/bin/bash -norc
#==============================================================
#
#  Abs:  Start the Matlab PV Checker Matlab script.  Meant to be used
#        by the daily cron job run by laci on lcls-daemon2
#
#  Name: MatlabPVChecker
#
#  Facility:  SLAC/LCLS
#
#  Auth: 27-Jan-2011, Mike Zelazny (zelazny@slac.stanford.edu)
#
#  Mod: 
#       16-Nov-2015 Mike Zelazny:
#         CATER 128683 - mailx doesn't like certain characters.
#         Use -v option for cat resolves this problem.
#       14-Nov-2015 Mike Zelazny:
#         Removed mccdev-dmz from email address.  Mail stopped 
#         coming out a few days ago.
#       12-Dec-2014 Jingchen Zhou
#         Added -glnx86 option to matlab
#==============================================================
#
DT=`date "+%D - %T"`
SLAC="@slac.stanford.edu"
MAILLIST="controls-software-reports$SLAC"
#
# Setup LCLS Environment
#
  if [ -f /usr/local/lcls/tools/script/ENVS.bash ]; then
    . /usr/local/lcls/tools/script/ENVS.bash
  fi

  if [ -e ${LCLS_ROOT}/tools/matlab/setup/matlabSetup.bash ]; then
    . ${LCLS_ROOT}/tools/matlab/setup/matlabSetup.bash

#
# Set appropriate EPICS_CA_MAX_ARRAY_BYTES
#
    unset EPICS_CA_MAX_ARRAY_BYTES

#
# For accounting purposes
#
    export MATLAB_STARTUP_SCRIPT=MatlabPVChecker

#
# Log file
#
    if [ -z $PHYSICS_USER ]
    then
      user=`whoami`
    else
      if [ none = $PHYSICS_USER ]
      then
        user=`whoami`
      else
        user=$PHYSICS_USER
      fi
    fi
    date=`date`
    year=`echo $date | cut -d" " -f6`-
    month=`echo $date | cut -d" " -f2`-
    day=`echo $date | cut -d" " -f3`-
    time=`echo $date | cut -d" " -f4 | cut -c1-5`

    if [ -e $MATLABDATAFILES/log ]; then
      log_file=$MATLABDATAFILES/log/MatlabPVChecker-$user-$year$month$day$time.log
    else
      log_file=MatlabPVChecker-$user-$year$month$day$time.log
    fi 
#
# Put the log file name in an environment variable for Matlab unix('printenv')
#
    export MATLAB_LOG_FILE_NAME=$log_file

#
# Start the Matlab script
#
    matlab -nosplash -nodesktop -glnx86 -r startLCLS,MatlabPVChecker -logfile $log_file

  else
    echo "Sorry, can't find LCLS environment setup"
  fi

cat -v $log_file | mailx -s "Matlab PV Checker ($DT)" $MAILLIST 
