#!/bin/bash -norc
#==============================================================
#
#  Abs:  Starts  Matlab scripts
#
#  Name: Matlab_startup_facet
#   $1 :  matlab script to start
#  [$2]:  Used by FeedbackGUI for config file
#  [$3]:  Used by FeedbackGUI for labeling log file
#
# ------------------------------------------------------------
# This script gets called from facethome which performs an
# SSH call to facet-srv02 and sets it's display to the
# Virtual frame buffer (XVFB) before launching this script.
# ------------------------------------------------------------
#
#  Facility:  SLAC
#
#  Auth: 31-Oct-2008, Brobeck
#         created from MatlabGUI by M. Zelazny
#
# Mod 
#
# 21-Jun-2011 jrock
#  FACET version
#  This version copies the facet version of java.opts to . so that matlab will connect to the
#  proper AIDA instance (SLACPROD)
#  For LCLS, java.opts for matlab is used in its default place: /usr/local/matlab/matlab75/bin/glnx86
#  To point a FACET matlab script to the SLACPROD AIDA instance, java.opts_facet is copied into
#  the current working directory and renamed to java.opts, where it is found by matlab when it starts up.
#
# 26-Apr-2010 Mike Zelazny
#  Set MATLAB_STARTUP_SCRIPT & MATLAB_LOG_FILE_NAME.
#
# 19-Nov-2008, Brobeck
#  added a $2 variable for use with the lcaInit,"$1('$2')" call
#  and $3 for labeling the log file
#
# 21-Nov-2008, Brobeck
#  Adding a log system to retain logs 
#
#==============================================================
#
# Make sure physics is running the script on facet-srv02
#

if  ! [ "$USER" = "fphysics" ] && ! [ `uname -n` = "facet-srv02" ]
  then 
     echo ""
     echo "This script must be run from the fphysics account"
     echo "on facet-srv02 - Preferably from facethome"
     echo ""
     exit
fi

# Set the display
#
OLD_DISP=`echo $DISPLAY`
export DISPLAY=:1.0

# 
# Setup FACET Environment
#
  if [ -e ${FACET_ROOT}/tools/matlab/setup/matlabSetup_facet.bash ]; then
     . ${FACET_ROOT}/tools/matlab/setup/matlabSetup_facet.bash

# copy in FACET version of java.opts file, which points matlab the the proper
# instance of AIDA
  if [ -f ${FACET_ROOT}/tools/matlab/setup/java.opts_facet ]; then
          wd=${PWD}
          cp ${FACET_ROOT}/tools/matlab/setup/java.opts_facet ${wd}/java.opts
  else
        echo 'No java.opts_facet found, exiting'
        exit 2;
  fi
#
# Log file on nfs -rename old one
#
    if [ -e $PHYSICS_DATA/log/matlab ]; then
      log_file=$PHYSICS_DATA/log/matlab/$1$3.log
    else
      log_file=$1$3.log
    fi 

    MDATE=`date '+%d_%b_%Y_%H_%M'`
    if [ -e $log_file ]; then
       /bin/mv -f ${log_file} ${log_file}-$MDATE
    fi

#
# For accounting purposes (see startup.m)
#
    export MATLAB_STARTUP_SCRIPT=$1
    export MATLAB_LOG_FILE_NAME=$log_file
#
# Start the Matlab script
#
    if [ "$2" = "" ]; then
	    echo "before xterm................................"
         /usr/bin/xterm -e matlab -glnx86 -nodesktop -nosplash -r $1  -logfile $log_file &
      else
         /usr/bin/xterm -e matlab -glnx86 -nodesktop -nosplash -r lcaInit,"$1('$2')"  -logfile $log_file &
    fi
    
    sleep 1
    export DISPLAY=$OLD_DISP
    xterm -e tail -f $log_file &

    #
    # log file cleanup -keep 5 log files
    #
    LOGCNT=`ls -t $PHYSICS_DATA/log/matlab/$1$3.log* | wc -l`
    if [ "$LOGCNT" -gt 5 ]; then
	y=`expr $LOGCNT - 5`
	for x in `ls -t  $PHYSICS_DATA/log/matlab/$1$3.log* | tail -n$y`
        do
	  /bin/rm -f $x
	done
    fi
  else
    echo "Sorry, can't find FACET environment setup"
  fi

