classdef UitoggletoolConverter < appmigration.internal.ComponentConverter
    %UIPUSHCONVERTER Converter for uitoggletool
    
    %   Copyright 2017-2020 The MathWorks, Inc.
    
    methods
        function [componentCreationFunction, issues] = getComponentCreationFunction(~, guideComponent)
            % GETCOMPONENTCREATIONFunction - Override superclass method.
            % Returns empty componentCreationFunction to signify it is not
            % supported and reports an issue
            
            import appmigration.internal.AppConversionIssueFactory;
            
            toolid = getappdata(guideComponent, 'toolid');
            clickedCallback = guideComponent.ClickedCallback;
            
            if ~isempty(toolid) && strcmp(clickedCallback, '%default') &&...
                    ismember(toolid, {....
                    'Annotation.InsertColorbar',...
                    'Annotation.InsertLegend'})
                
                % The predefined toggletool is unsupported and so create an
                % issue that will be reported.
                
                componentCreationFunction = [];
                
                issues = AppConversionIssueFactory.createComponentIssue(...
                    AppConversionIssueFactory.Ids.UnsupportedComponentPredefinedUitool, guideComponent.Tag, guideComponent.Type);
                
                % Set the name to be like: 'uitoggletool (InsertColorbar)'
                toolidName = strsplit(toolid, '.');
                toolidName = toolidName{2};
                issues.Name = sprintf('%s (%s)', issues.Name, toolidName);
                
            elseif ~isempty(toolid) && strcmp(clickedCallback, '%default') &&...
                    ismember(toolid, {....
                    'Exploration.ZoomIn',...
                    'Exploration.ZoomOut',...
                    'Exploration.Pan',...
                    'Exploration.Rotate',...
                    'Exploration.DataCursor'})

                % The predefined toggletool is supported on the axes
                % toolbar so don't migrate and don't report an issue.
                
                componentCreationFunction = [];
                issues = [];
            else            
                % The toggletool is a custom tool and is supported
                % programmatically so migrate it and create an issue that
                % will cause code to be generated.
                
                componentCreationFunction = @uitoggletool;

                issues = AppConversionIssueFactory.createComponentIssue(...
                    AppConversionIssueFactory.Ids.UnsupportedComponentUitoggletool, guideComponent.Tag,  guideComponent.Type);

                % Assign to the value additional details needed for
                % generating code for the pushtool
                issues.Value = struct(...
                    'ParentTag', guideComponent.Parent.Tag,...
                    'ComponentClass', class(guideComponent),...
                    'ChildrenTag', [],...
                    'ChildrenType', []);
            end
        end
        
        function conversionFuncs = getCallbackConversionFunctions(~, guideComponent)
            import appmigration.internal.CommonCallbackConversionUtil;
            
            % Need to specify callback conversion functions so that the
            % ComponentConverter.convert() can identify the callback names
            % for this component and add them to the list of unsupported
            % callbacks so that the code doesn't get migrated over.
            
            toolid = getappdata(guideComponent, 'toolid');
            clickedCallback = guideComponent.ClickedCallback;
            
            if ~isempty(toolid) && strcmp(clickedCallback, '%default')
                % The tool is a predefined tool which are not supported or
                % have now been moved to the axes toolbar. We don't want to
                % generate code for these toolbar callbacks.
                
                conversionFuncs = {...
                    {'ButtonDownFcn'  , @CommonCallbackConversionUtil.convertCallbackForUnsupportedComponent},...
                    {'ClickedCallback', @CommonCallbackConversionUtil.convertCallbackForUnsupportedComponent},...
                    {'CreateFcn'      , @CommonCallbackConversionUtil.convertCallbackForUnsupportedComponent},...
                    {'DeleteFcn'      , @CommonCallbackConversionUtil.convertCallbackForUnsupportedComponent},...
                    {'OffCallback'    , @CommonCallbackConversionUtil.convertCallbackForUnsupportedComponent},...
                    {'OnCallback'     , @CommonCallbackConversionUtil.convertCallbackForUnsupportedComponent},...
                    };
            else
                conversionFuncs = {...
                    {'ButtonDownFcn'  , @CommonCallbackConversionUtil.convertUnsupportedCallback},...
                    {'ClickedCallback', @CommonCallbackConversionUtil.convertCallbackWithProgrammaticWorkaround},...
                    {'CreateFcn'      , @CommonCallbackConversionUtil.convertCreateFcn},...
                    {'DeleteFcn'      , @CommonCallbackConversionUtil.convertCallbackWithProgrammaticWorkaround},...
                    {'OffCallback'    , @CommonCallbackConversionUtil.convertCallbackWithProgrammaticWorkaround},...
                    {'OnCallback'     , @CommonCallbackConversionUtil.convertCallbackWithProgrammaticWorkaround},...
                    };
            end
        end
        
        function conversionFuncs = getPropertyConversionFunctions(~)
            import appmigration.internal.CommonPropertyConversionUtil;
            import appmigration.internal.AppConversionIssueFactory;
            
            conversionFuncs = {...
                {'BusyAction'         , CommonPropertyConversionUtil.reportUnsupportedPropertyIfValueIsNot('queue', AppConversionIssueFactory.Ids.UnsupportedPropertyToolbarBusyAction)},...
                {'CData'              , CommonPropertyConversionUtil.reportUnsupportedPropertyIfValueIsNot([]     , AppConversionIssueFactory.Ids.UnsupportedPropertyToolbarCData)},...
                {'Enable'             , CommonPropertyConversionUtil.reportUnsupportedPropertyIfValueIsNot('on'   , AppConversionIssueFactory.Ids.UnsupportedPropertyToolbarEnable)},...
                {'HandleVisibility'   , CommonPropertyConversionUtil.reportUnsupportedPropertyIfValueIsNot('on'   , AppConversionIssueFactory.Ids.UnsupportedPropertyToolbarHandleVisibility)},...
                {'Interruptible'      , CommonPropertyConversionUtil.reportUnsupportedPropertyIfValueIsNot('on'   , AppConversionIssueFactory.Ids.UnsupportedPropertyToolbarInterruptible)},...
                {'Separator'          , CommonPropertyConversionUtil.reportUnsupportedPropertyIfValueIsNot('off'  , AppConversionIssueFactory.Ids.UnsupportedPropertyToolbarSeparator)},...
                {'State'              , CommonPropertyConversionUtil.reportUnsupportedPropertyIfValueIsNot('off'  , AppConversionIssueFactory.Ids.UnsupportedPropertyToolbarState)},...
                {'Tag'                , CommonPropertyConversionUtil.reportUnsupportedPropertyIfValueIsNot(''     , AppConversionIssueFactory.Ids.UnsupportedPropertyToolbarTag)},...
                {'Tooltip'            , CommonPropertyConversionUtil.reportUnsupportedPropertyIfValueIsNot(''     , AppConversionIssueFactory.Ids.UnsupportedPropertyToolbarTooltip)},...
                {'UserData'           , @CommonPropertyConversionUtil.convertUserData},...
                {'Visible'            , CommonPropertyConversionUtil.reportUnsupportedPropertyIfValueIsNot('on'   , AppConversionIssueFactory.Ids.UnsupportedPropertyToolbarVisible)},...
                };
            % Properties Implicitly Converted
            %   Parent
            %   Children
            
            % Properties NOT converted and NOT reported:
            %   Not Applicable/Dropped
            %       BeingDeleted - Read-only
            %       ContextMenu - No effect
            %       HitTest - Dropped
            %       Type - Read-only
        end
    end
end