%This is the GUI for the Image Analysis application
function mainFig = imgAnalysis_gui
MARGIN_SIZE = 5;
IMAGE_WIDTH = 320;
IMAGE_HEIGHT = 240;

%WINDOW SIZE AND POSITION
winWidth = IMAGE_WIDTH * 2 + 11 * MARGIN_SIZE; %arbitrary value
winHeight = 710; %arbitrary value
screenSize = get(0, 'screensize'); %[left, bottom, width, height]
screenWidth = screenSize(3);
screenHeight = screenSize(4);
%centre of the screen
winPosition =...
[...
    0.5 * (screenWidth - winWidth),...
    0.5 * (screenHeight - winHeight),...
    winWidth,...
    winHeight...
]; %[left, bottom, width, height]
mainFig = figure...
(...
'handleVisibility', 'callback',...
'invertHardcopy','off',...
'menubar', 'none',...
'name', 'Image Analysis',...
'numberTitle', 'off',...
'paperPositionMode', 'auto',...
'position', winPosition,...
'toolbar', 'none',...
'windowstyle', 'normal',...
'visible', 'off'... %hide the GUI while it's being constructed
);%all other properties are default

%%%%%
%   WIDGETS
%%%%%
%pushbutton
previousButton = uicontrol...
(...
mainFig,...%parent
'busyAction', 'cancel',...
'string', 'Previous image',...
'style', 'pushbutton',...
'tag', 'previousButton'...
);%all other properties are default
nextButton = uicontrol...
(...
mainFig,...%parent
'busyAction', 'cancel',...
'string', 'Next image',...
'style', 'pushbutton',...
'tag', 'nextButton'...
);%all other properties are default
logBookButton = uicontrol...
(...
mainFig,...%parent
'busyAction', 'cancel',...
'string', '-> Log Book',...
'style', 'pushbutton',...
'tag', 'logBookButton'...
);%all other properties are default
adjustCropAreaButton = uicontrol...
(...
mainFig,...%parent
'busyAction', 'cancel',...
'string', 'Adjust crop area...',...
'style', 'pushbutton',...
'tag', 'adjustCropAreaButton'...
);%all other properties are default

%text
infoText = uicontrol...
(...
mainFig,...%parent
'horizontalAlignment', 'right',...
'string', '12-04-1982 12:00:00.000',...
'style', 'text',...
'tag', 'infoText'...
);%all other properties are default
fitResultsText = uicontrol...
(...
mainFig,...
'horizontalAlignment', 'left',...
'string', {'dx = 0.1mm', '{\itAe}^{-\alpha\itt}sin\beta{\itt} \alpha<<\beta', 'dy = 0.2mm'},...%test values
'style', 'text',...
'tag', 'fitResultsText'...
);%all other properties are default

%panel
imgAxesPanel = uipanel(...
    'borderType', 'none',...
    'parent', mainFig,...
    'tag', 'imgAxesPanel',...
    'title', '',...
    'units', 'pixels');

%axes
imgAxes =axes...
(...
'color', 'none',...
'parent', imgAxesPanel,...
'tag', 'imgAxes',...
'units', 'pixels',...%position
'visible', 'off'...
);%all other properties are default
xPlaneAxes = axes...
(...
'parent', mainFig,...
'tag', 'xPlaneAxes',...
'units', 'pixels'...%position
);%all other properties are default
yPlaneAxes = axes...
(...
'parent', mainFig,...
'tag', 'yPlaneAxes',...
'units', 'pixels'...%position
);%all other properties are default   

%change widget size (widget, width, height)
imgUtil_setWidgetSize(nextButton, 80, -1);
imgUtil_setWidgetSize(previousButton, 100, -1);
imgUtil_setWidgetSize(infoText, winWidth - 260 - 6 * MARGIN_SIZE, -1);
imgUtil_setWidgetSize(logBookButton, 80, -1);

imgUtil_setWidgetSize(xPlaneAxes, IMAGE_WIDTH, IMAGE_HEIGHT - 20);
imgUtil_setWidgetSize(yPlaneAxes, IMAGE_WIDTH - 20, IMAGE_HEIGHT);

imgUtil_setWidgetSize(imgAxesPanel, IMAGE_WIDTH, IMAGE_HEIGHT);
imgUtil_setWidgetSize(imgAxes, IMAGE_WIDTH, IMAGE_HEIGHT);
imgUtil_setWidgetSize(adjustCropAreaButton, 120, -1);

imgUtil_setWidgetSize(fitResultsText, IMAGE_WIDTH, 135);

%%%%%
%   MISC
%%%%%
%set window bg color to widget bg color
set(mainFig, 'color', get(infoText, 'backgroundColor'));

%debug
%set(fitResultsText, 'backgroundColor', [0.34 0 0.5]);
% set(imgAxesPanel, 'backgroundColor', [1 0.5 0]);

%%%%%
%   LAYOUT (from top)
%%%%%

% next/previous buttons, image/timestamp text
rowLeft = 2 * MARGIN_SIZE;
rowBottom = winHeight - 5 * MARGIN_SIZE;
imgUtil_rowLayout(...
    [previousButton, nextButton, infoText, logBookButton],...
    [0, 0, -4, 0],...
    rowLeft, rowBottom, MARGIN_SIZE); 

% image processing panel
rowBottom = imgProcessing_panel(mainFig, rowLeft, rowBottom - 2 * MARGIN_SIZE);
handles = guihandles(mainFig);
imgUtil_setWidgetSize(handles.beamSizeUnitsText, 85, -1);
rowBottom = rowBottom + 8 * MARGIN_SIZE;
imgUtil_rowLayout(...
    [handles.autoApplyCheckbox, handles.applyButton],...
    [0, 0],...
    winWidth - 105 - MARGIN_SIZE,...
    rowBottom, MARGIN_SIZE); 

%progress panel
rowBottom = progress_panel(mainFig, rowLeft, rowBottom, winWidth - 3 * MARGIN_SIZE);

%
rowBottom = rowBottom - IMAGE_HEIGHT - 4 * MARGIN_SIZE;
imgUtil_rowLayout(...
    [yPlaneAxes, imgAxesPanel],...
    [0, 0],...
    rowLeft + 30, rowBottom, 6 * MARGIN_SIZE); 
%
rowBottom = rowBottom - 5 * MARGIN_SIZE;
imgUtil_rowLayout(...
    [adjustCropAreaButton],...
    [0],...
    winWidth - MARGIN_SIZE - 120, rowBottom, MARGIN_SIZE);

%
rowBottom = rowBottom - 10 * MARGIN_SIZE;
imgUtil_rowLayout(...
    [handles.showCentroidText, handles.currentCentroidCheckbox],...
    [-4, 0],...
    rowLeft,...
    rowBottom, MARGIN_SIZE); 
%
rowBottom = rowBottom - 5 * MARGIN_SIZE;
imgUtil_rowLayout(...
    [handles.colormapText, handles.colormapFcnPopupmenu,...
    handles.bppSlider, handles.bppText, handles.autoBppCheckbox],...
    [-4, 0, 0, -4, 0],...
    rowLeft, rowBottom, MARGIN_SIZE + 1);

%
rowBottom = rowBottom - 5 * MARGIN_SIZE;
imgUtil_rowLayout(...
    [handles.algPopupmenu, handles.beamSizeUnitsText, handles.beamSizeUnitsPopupmenu],...
    [0, -4, 0],...
    rowLeft, rowBottom, MARGIN_SIZE);

% 
rowBottom = rowBottom - IMAGE_HEIGHT + 6 * MARGIN_SIZE;
imgUtil_rowLayout(...
    [fitResultsText],...
    [0],...
    rowLeft,...
    8, 0); 

%
imgUtil_rowLayout(...
    [xPlaneAxes],...
    [0],...
    rowLeft + IMAGE_WIDTH + 8 * MARGIN_SIZE,...
    23,...
    0); 

%img axes
pos = get(imgAxes, 'position');
pos(1) = pos(1) - 42;
pos(2) = pos(2) - 26;
set(imgAxes, 'position', pos);

%make GUI visible
set(mainFig, 'visible', 'on');