%This is the GUI for the Image Browser application
function mainFig = imgBrowser_gui(nrDsTabs)
% imageAnalysisGUI These comments are displayed at the command line 
%       in response to the help command.
if nargin < 1
    nrDsTabs = 8;
end
MARGIN_SIZE = 5;
NR_VISIBLE_IMAGE_ROWS = 2;
NR_IMAGES_PER_ROW = 3;
NR_DS_BUTTONS = nrDsTabs;
MAX_NR_VISIBLE_IMAGES = NR_VISIBLE_IMAGE_ROWS * NR_IMAGES_PER_ROW;
IMG_PANEL_WIDTH = 210;
IMG_PANEL_HEIGHT = 100;


%WINDOW SIZE AND POSITION
winWidth = IMG_PANEL_WIDTH * NR_IMAGES_PER_ROW + 12 * MARGIN_SIZE; %arbitrary value
winHeight = 4 * IMG_PANEL_HEIGHT + 450;
screenSize = get(0, 'screensize'); %[left, bottom, width, height]
screenWidth = screenSize(3);
screenHeight = screenSize(4);
%centre of the screen
winPosition =...
[...
    0.5 * (screenWidth - winWidth),...
    0.5 * (screenHeight - winHeight),...
    winWidth,...
    winHeight...
]; %[left, bottom, width, height]
mainFig = figure...
(...
'handleVisibility', 'callback',...
'invertHardcopy','off',...
'menubar', 'none',...
'name', 'Image Browser',...
'numberTitle', 'off',...
'paperPositionMode', 'auto',...
'position', winPosition,...
'toolbar', 'none',...
'windowstyle', 'normal',...
'visible', 'off'... %hide the GUI while it's being constructed
);%all other properties are default

%%%%%
%   WIDGETS
%%%%%
%pushbutton
removeDSButton = uicontrol...
(...
mainFig,...%parent
'busyAction', 'cancel',...
'fontWeight', 'bold',...
'foregroundColor', [1 0 0],...
'style', 'pushbutton',...
'tag', 'removeDSButton'...
);%all other properties are default

xProjectionButton = uicontrol...
(...
mainFig,...%parent
'busyAction', 'cancel',...
'string', 'X projection',...
'style', 'pushbutton',...
'tag', 'xProjectionButton'...
);%all other properties are default
yProjectionButton = uicontrol...
(...
mainFig,...%parent
'busyAction', 'cancel',...
'string', 'Y projection',...
'style', 'pushbutton',...
'tag', 'yProjectionButton'...
);%all other properties are default
masterCropAreaButton = uicontrol...
(...
mainFig,...%parent
'busyAction', 'cancel',...
'string', 'Master crop area...',...
'style', 'pushbutton',...
'tag', 'masterCropAreaButton'...
);%all other properties are default
logBookButton = uicontrol...
(...
mainFig,...%parent
'busyAction', 'cancel',...
'string', '-> Log Book',...
'style', 'pushbutton',...
'tag', 'logBookButton'...
);%all other properties are default

%text
imgOffsetText = uicontrol...
(...
mainFig,...%parent
'horizontalAlignment', 'right',...
'string', 'Jump to image #',...
'style', 'text',...
'tag', 'goToButton'...
);%all other properties are default

%slider
imgRowSlider = uicontrol...
(...
mainFig,...%parent
'max', 2,...%to be configured
'min', 1,...
'style', 'slider',...
'tag', 'imgRowSlider',...
'value', 1 ...
);%all other properties are default

%popupmenu
dsPopupmenu = uicontrol...
(...
mainFig,...%parent
'string', 'dummy',...
'style', 'popupmenu',...
'tag', 'dsPopupmenu'...
);%all other properties are default
imgOffsetPopupmenu = uicontrol...
(...
mainFig,...%parent
'string', '234',...
'style', 'popupmenu',...
'tag', 'imgOffsetPopupmenu'...
);%all other properties are default

%sets of widgets
for i=1:NR_DS_BUTTONS
    dsButtons(i) = uicontrol...
        (...
        mainFig,...%parent
        'busyAction', 'cancel',...
        'string', sprintf('DataSet #%d', i),...
        'style', 'pushbutton',...
        'tag', sprintf('dsButton%d', i)...
        );%all other properties are default
end

for i=1:MAX_NR_VISIBLE_IMAGES
    imgIndexText(i) = uicontrol...
        (...
        mainFig,...%parent
        'horizontalAlignment', 'left',...
        'string', '#22',...%test value
        'style', 'text',...
        'tag', sprintf('imgIndexText%d',i)...
        );%all other properties are default
    
    imgCheckbox(i) = uicontrol...
        (...
        mainFig,...%parent
        'style', 'checkbox',...
        'tag', sprintf('imgCheckbox%d',i),...
        'value', 1 ...
        );%all other properties are defau

    imgTimestampText(i) = uicontrol...
        (...
        mainFig,...%parent
        'fontSize', 9,...
        'horizontalAlignment', 'right',...
        'string', '10-10-2006 18:00:05.741',...%test value
        'style', 'text',...
        'tag', sprintf('imgTimestampText%d',i)...
        );%all other properties are default
    
    imgAxesPanel(i) = uipanel(...
        'borderType', 'none',...
        'parent', mainFig,...
        'tag', sprintf('imgAxesPanel%d', i),...
        'title', '',...
        'units', 'pixels');
    
    imgAxes(i) = axes...
        (...
        'color', 'none',...
        'parent', imgAxesPanel(i),...
        'tag', sprintf('imgAxes%d', i),...
        'units', 'pixels',...%position
        'visible', 'off'...
        );%all other properties are default
    
    imgAnalysisButton(i) = uicontrol...
        (...
        mainFig,...%parent
        'busyAction', 'cancel',...
        'string', 'Analyze...',...
        'style', 'pushbutton',...
        'tag', sprintf('imgAnalysisButton%d', i)...
        );%all other properties are default
    
    imgFitAxes(i) = axes...
        (...
        'parent', mainFig,...
        'tag', sprintf('imgFitAxes%d',i),...
        'units', 'pixels'...%position,
        );%all other properties are default
end

%change widget size (widget, width, height)
imgUtil_setWidgetSize(dsPopupmenu, 38, 17);

imgUtil_setWidgetSize(removeDSButton, 12, 12);

imgUtil_setWidgetSize(xProjectionButton, 80, -1);
imgUtil_setWidgetSize(yProjectionButton, 80, -1);
imgUtil_setWidgetSize(masterCropAreaButton, 115, -1);
imgUtil_setWidgetSize(logBookButton, 80, -1);

imgUtil_setWidgetSize(imgRowSlider, 15, 4 * IMG_PANEL_HEIGHT + 150);

imgUtil_setWidgetSize(imgOffsetText, 100, -1);
imgUtil_setWidgetSize(imgOffsetPopupmenu, 35, -1);

dsButtonWidth = (winWidth - 85)/NR_DS_BUTTONS;
for i=1:NR_DS_BUTTONS
    imgUtil_setWidgetSize(dsButtons(i), dsButtonWidth, -1);
end
for i=1:MAX_NR_VISIBLE_IMAGES
    imgUtil_setWidgetSize(imgCheckbox(i), 16, 16);
    imgUtil_setWidgetSize(imgIndexText(i), 27, -1);
    imgUtil_setWidgetSize(imgTimestampText(i), IMG_PANEL_WIDTH - 43 - 5 * MARGIN_SIZE, 11);
    imgUtil_setWidgetSize(imgAxesPanel(i), IMG_PANEL_WIDTH - 40, IMG_PANEL_HEIGHT);
    imgUtil_setWidgetSize(imgAxes(i), IMG_PANEL_WIDTH - 40, IMG_PANEL_HEIGHT);
    imgUtil_setWidgetSize(imgAnalysisButton(i), 60, -1);
    imgUtil_setWidgetSize(imgFitAxes(i), IMG_PANEL_WIDTH - 40, IMG_PANEL_HEIGHT);
end

%%%%%
%   MISC
%%%%%
defaultBgColor = get(removeDSButton, 'backgroundColor');
set(mainFig, 'color', defaultBgColor);
% set(infoText, 'backgroundColor', [1 0 0]);
% set(imgIndexText(1), 'backgroundColor', [1 0 1]);
% set(goToText, 'backgroundColor', [1 0 1]);

%icon
try
    icon = imread('icon_remove.png', 'png', 'BackgroundColor', defaultBgColor);
    set(removeDSButton, 'CData', icon);
catch
    %do nothing
end
%%%%%
%   LAYOUT (from top)
%%%%%

% datasets
rowLeft = 3 * MARGIN_SIZE;
rowBottom = winHeight - 19;
imgUtil_rowLayout(...
    [removeDSButton],...
    [0],...
    rowLeft, rowBottom + 4, 0); 
marginArray = zeros(1, NR_DS_BUTTONS);
imgUtil_rowLayout(...
    dsButtons,...
    marginArray,...
    rowLeft + 14, rowBottom, 0);
imgUtil_rowLayout(...
    dsPopupmenu,...
    [0],...
    winWidth - 38 - MARGIN_SIZE, rowBottom + 4, 0);

% image processing panel
rowBottom = imgProcessing_panel(mainFig, rowLeft, rowBottom - 2 * MARGIN_SIZE);

handles = guihandles(mainFig);
imgUtil_setWidgetSize(handles.beamSizeUnitsText, 90, -1);
imgUtil_setWidgetSize(handles.algPopupmenu, 165, -1);

rowBottom = rowBottom + 9 * MARGIN_SIZE;
imgUtil_rowLayout(...
    [handles.autoApplyCheckbox, handles.applyButton],...
    [0, 0],...
    winWidth - 2 * MARGIN_SIZE - 100,...
    rowBottom, MARGIN_SIZE); 

%progress panel
rowBottom = progress_panel(mainFig, rowLeft, rowBottom, winWidth - 3 * MARGIN_SIZE);

%
rowBottom = rowBottom - 6 * MARGIN_SIZE;

imgUtil_rowLayout(...
    [handles.algPopupmenu],...
    [0],...
    rowLeft,...
    rowBottom, MARGIN_SIZE); 

imgUtil_rowLayout(...
    [handles.showCentroidText, handles.currentCentroidCheckbox],...
    [-4, 0],...
    rowLeft + 315,...
    rowBottom, MARGIN_SIZE); 

%
rowBottom = rowBottom - 5 * MARGIN_SIZE;

imgUtil_rowLayout(...
    [handles.beamSizeUnitsText, handles.beamSizeUnitsPopupmenu],...
    [-4, 0],...
    rowLeft,...
    rowBottom, MARGIN_SIZE + 3); 

imgUtil_rowLayout(...
    [handles.colormapText, handles.colormapFcnPopupmenu,...
    handles.bppSlider, handles.bppText, handles.autoBppCheckbox],...
    [-4, 0, 0, -4, 0],...
    rowLeft + 315, rowBottom, MARGIN_SIZE + 1);

%
rowBottom = rowBottom - 6 * MARGIN_SIZE;
imgUtil_rowLayout(...
    [xProjectionButton, yProjectionButton],...
    [0, 0],...
    rowLeft, rowBottom, 0); 

imgUtil_rowLayout(...
    [imgOffsetText, imgOffsetPopupmenu],...
    [-4, 0],...
    winWidth - 135 - 2 * MARGIN_SIZE, rowBottom, MARGIN_SIZE); 


%%%%%
%
rowBottom = rowBottom - 6 * MARGIN_SIZE;
imgUtil_rowLayout(...
    [...
    imgCheckbox(1), imgIndexText(1), imgTimestampText(1)],...
    [0, -6, 2],...
    rowLeft, rowBottom, MARGIN_SIZE); 
imgUtil_rowLayout(...
    [...
    imgCheckbox(2), imgIndexText(2), imgTimestampText(2)],...
    [0, -6, 2],...
    rowLeft + IMG_PANEL_WIDTH + MARGIN_SIZE, rowBottom, MARGIN_SIZE); 
imgUtil_rowLayout(...
    [...
    imgCheckbox(3), imgIndexText(3), imgTimestampText(3)],...
    [0, -6, 2],...
    rowLeft + 2 * (IMG_PANEL_WIDTH + MARGIN_SIZE), rowBottom, MARGIN_SIZE); 
%
rowBottom = rowBottom - 2 * MARGIN_SIZE - IMG_PANEL_HEIGHT;
imgUtil_rowLayout(...
    [...
    imgAxesPanel(1), imgAxesPanel(2), imgAxesPanel(3)],...
    [0, 0, 0],...
    rowLeft + 28, rowBottom, MARGIN_SIZE + 40); 

%
rowBottom = rowBottom - 4 * MARGIN_SIZE;
imgUtil_rowLayout(...
    [...
    imgAnalysisButton(1), imgAnalysisButton(2), imgAnalysisButton(3)],...
    [0, 0, 0],...
    rowLeft + IMG_PANEL_WIDTH - 60 - 10, rowBottom - 3, IMG_PANEL_WIDTH + MARGIN_SIZE - 60); 
%
rowBottom = rowBottom - MARGIN_SIZE - IMG_PANEL_HEIGHT;%room for occasional 10^4
imgUtil_rowLayout(...
    [imgFitAxes(1), imgFitAxes(2), imgFitAxes(3)],...
    [0, 0, 0],...
    rowLeft + 28, rowBottom, MARGIN_SIZE + 40);

%%%%
%
rowBottom = rowBottom -12 * MARGIN_SIZE;
imgUtil_rowLayout(...
    [...
    imgCheckbox(4), imgIndexText(4), imgTimestampText(4)],...
    [0, -6, 2],...
    rowLeft, rowBottom, MARGIN_SIZE); 
imgUtil_rowLayout(...
    [...
    imgCheckbox(5), imgIndexText(5), imgTimestampText(5)],...
    [0, -6, 2],...
    rowLeft + IMG_PANEL_WIDTH + MARGIN_SIZE, rowBottom, MARGIN_SIZE); 
imgUtil_rowLayout(...
    [...
    imgCheckbox(6), imgIndexText(6), imgTimestampText(6)],...
    [0, -6, 2],...
    rowLeft + 2 * (IMG_PANEL_WIDTH + MARGIN_SIZE), rowBottom, MARGIN_SIZE); 

%
rowBottom = rowBottom - 2 * MARGIN_SIZE - IMG_PANEL_HEIGHT;
imgUtil_rowLayout(...
    [...
    imgAxesPanel(4), imgAxesPanel(5), imgAxesPanel(6)],...
    [0, 0, 0],...
    rowLeft + 28, rowBottom, MARGIN_SIZE + 40); 
%
rowBottom = rowBottom - 4 * MARGIN_SIZE;
imgUtil_rowLayout(...
    [...
    imgAnalysisButton(4), imgAnalysisButton(5), imgAnalysisButton(6)],...
    [0, 0, 0],...
    rowLeft + IMG_PANEL_WIDTH - 60 - 10, rowBottom - 3, IMG_PANEL_WIDTH + MARGIN_SIZE - 60); 
%
rowBottom = rowBottom - MARGIN_SIZE - IMG_PANEL_HEIGHT;%room for occasional 10^4
imgUtil_rowLayout(...
    [imgFitAxes(4), imgFitAxes(5), imgFitAxes(6)],...
    [0, 0, 0],...
    rowLeft + 28, rowBottom, MARGIN_SIZE + 40);

%
imgUtil_rowLayout(...
    [masterCropAreaButton],...
    [0],...
    rowLeft, 5, 0); 
imgUtil_rowLayout(...
    [logBookButton],...
    [0],...
    winWidth - 85, 5, 0); 
%
imgUtil_rowLayout(...
    [imgRowSlider],...
    [0],...
    winWidth - 4 * MARGIN_SIZE,...
    50, 0); 

%axes
for i=1:MAX_NR_VISIBLE_IMAGES
    pos = get(imgAxes(i), 'position');
    pos(1) = pos(1) - 23;
    pos(2) = pos(2) - 16;
    set(imgAxes(i), 'position', pos);
end

%set GUI visible
set(mainFig, 'visible', 'on');