function imgProcessing_annotation_showAxesLabel(imgAxes, ipParam)
axLabel = get(imgAxes, 'xlabel');
set(axLabel,...
    'units', 'normalized',...
    'position', [-0.02 1.02 0],...
    'string', ipParam.beamSizeUnits);