function mainFig = imgUtil_gui_detachedLiveImg()

%WINDOW SIZE AND POSITION
winWidth = 640;
winHeight = 480;
screenSize = get(0, 'screensize'); %[left, bottom, width, height]
screenWidth = screenSize(3);
screenHeight = screenSize(4);
%centre of the screen
winPosition =...
[...
    0.5 * (screenWidth - winWidth),...
    0.5 * (screenHeight - winHeight),...
    winWidth,...
    winHeight...
]; %[left, bottom, width, height]
mainFig = figure...
(...
'handleVisibility', 'callback',...
'position', winPosition,...
'tag', 'liveImgFig',...
'visible', 'off'... %hide, while the GUI is being constructed
);%all other properties are default


%axes
axes(...
'color', 'none',...
'parent', mainFig,...
'tag', 'imgAxes',...
'visible', 'on'...
);%all other properties are default


%make GUI visible
set(mainFig, 'visible', 'on');