function s = imgUtil_fitResults2String(stats,units)

%XMEAN YMEAN XRMS YRMS CORR SUM
s{1}= ...
    sprintf('XMEAN........%.0f  %s', stats(1), units);
s{2}= ...
    sprintf('YMEAN........%.0f  %s', stats(2), units);
s{3}= ...
    sprintf('XRMS...........%.0f  %s', stats(3), units);
s{4}= ...
    sprintf('YRMS...........%.0f  %s', stats(4), units);
s{5}= ...
    sprintf('CORR...........%.0f  %s%s', stats(5), units, '^2');
s{6}= ...
    sprintf('SUM.............%.0f  counts',  stats(6));