function [index, flag] = imgUtil_dialog_saveCentroid()
[index, flag] = listdlg(...
    'listSize', [150 33],...
    'listString',{'Golden orbit', 'Laser beam'},...
    'name', 'Image Acquisition',...
    'promptString', 'Save current centroid as...',...
    'selectionMode', 'single'...
    );