function h = imgUtil_dialog_setPVMonitors()
h = helpdlg(...
    sprintf('%s %s',...
    'Please wait until the application has set up PV monitors.',...
    'This may take some time when PVs are not accessible.'),...
    'Image Acquisiton');