function selection = imgUtil_dialog_keepMasterCrop()
selection = listdlg(...
    'listSize', [360 33],...
    'listString',{'keep master crop height', 'keep master crop width'},...
    'name', 'Keep Master Crop... ?',...
    'promptString', {'Coordinates of the upper left corner of the new crop area ';...
                     'have been applied. Now you can choose to:';...
                     ''});%otherwise unreadable