function newRowBottom = progress_panel(parent, rowLeft, rowBottom, width)

MARGIN_SIZE = 5;
%axes
progressAxes = axes...
(...
'parent', parent,...
'tag', 'progressAxes',...
'units', 'pixels',...%position,
'visible', 'off',...
'xLim', [0 100]...
);%all other properties are default
image...
(...
'cdata', 1,...
'parent', progressAxes,...
'tag', 'progressImage',...
'visible', 'on'...
);%all other properties are default
progressMessageText = uicontrol...
(...
parent,...%parent
'horizontalAlignment', 'left',...
'string', 'This is the progress...',...
'style', 'text',...
'tag', 'progressMessageText'...
);%all other properties are default
estTimeLeftText = uicontrol...
(...
parent,...%parent
'horizontalAlignment', 'right',...
'string', '(est. time left: 140 secs)',...
'style', 'text',...
'tag', 'estTimeLeftText'...
);%all other properties are default

EST_TIME_LEFT_TEXT_WIDTH = 150;
imgUtil_setWidgetSize(progressMessageText, width - EST_TIME_LEFT_TEXT_WIDTH - 2 * MARGIN_SIZE, -1);
imgUtil_setWidgetSize(estTimeLeftText, EST_TIME_LEFT_TEXT_WIDTH, -1);
imgUtil_setWidgetSize(progressAxes, width, 5);

% set(progressMessageText, 'backgroundColor', [1 0 0]);
% set(estTimeLeftText, 'backgroundColor', [0 1 0]);

rowBottom = rowBottom - 6 * MARGIN_SIZE;

imgUtil_rowLayout(...
    [progressMessageText, estTimeLeftText],...
    [0, 0],...
    rowLeft, rowBottom, MARGIN_SIZE);
rowBottom = rowBottom - 2 * MARGIN_SIZE;
imgUtil_rowLayout(...
    [progressAxes],...
    [0],...
    rowLeft, rowBottom, MARGIN_SIZE);

newRowBottom = rowBottom;

